import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, resolve, relative, dirname } from "node:path";

function isSourceFile(file, exts) {
	const clean = file.split("?")[0];
	return !clean.endsWith(".d.ts") && exts.some(e => clean.endsWith(e));
}

async function walk(dir, exts) {
	try {
		const dns = await readdir(dir, { withFileTypes: true });
		const f = await Promise.all(dns.map(d => {
			if (d.name === "node_modules" || d.name.startsWith(".")) return [];
			const p = join(dir, d.name);
			return d.isDirectory() ? walk(p, exts) : resolve(p);
		}));
		return f.flat().filter(file => isSourceFile(file, exts));
	} catch {
		return [];
	}
}

function catchDefaultExport(code, file, map) {
	const rx = /export\s+default\s+(?:async\s+)?(?:function\s+|class\s+)?\s*([A-Z][\w$]*)/;
	const m = code.match(rx);
	if (!m) return false;

	const name = m[1];
	let old = null;

	for (const key in map) if (map[key] === file) old = key;
	if (old === name) return false;

	if (old) delete map[old];
	map[name] = file;
	return true;
}

async function writeDeclarationFile(map, dtsPath) {
	const dtsDir = dirname(dtsPath);
	// 1. Start with global declaration block
	let content = "// This file was generated by auto-imports\ndeclare global {";

	for (const name in map) {
		const rel = relative(dtsDir, map[name]).replace(/\\/g, "/").replace(/\.[jt]sx?$/, "");
		const path = rel.startsWith(".") ? rel : `./${rel}`;
		content += `\n	const ${name}: typeof import("${path}").default;`;
	}

	// 2. Close block and add export to mark as module
	content += "\n}\n\nexport {};";

	try {
		await mkdir(dtsDir, { recursive: true });
		await writeFile(dtsPath, content);
	} catch (e) {
		console.error(`Failed dts: ${e.message}`);
	}
}

function findUppercaseWords(code) {
	const clean = code.replace(/\/\*[\s\S]*?\*\/|\/\/.*/g, "");
	const matches = clean.match(/\b[A-Z][\w$]*\b/g);
	return [...new Set(matches || [])];
}

export default function autoImports(options = {}) {
	const opts = {
		src: "src",
		extensions: [".js", ".jsx", ".ts", ".tsx"],
		dts: "src/global.d.ts",
		...options
	};
	let exportMap = {};

	const refreshMap = async (server) => {
		const files = await walk(resolve(process.cwd(), opts.src), opts.extensions);
		const newMap = {};

		for (const f of files) {
			try {
				const code = await readFile(f, "utf8");
				catchDefaultExport(code, f, newMap);
			} catch { continue; }
		}

		if (JSON.stringify(newMap) !== JSON.stringify(exportMap)) {
			exportMap = newMap;
			await writeDeclarationFile(exportMap, resolve(process.cwd(), opts.dts));
			if (server) server.moduleGraph.invalidateAll();
		}
	};

	return {
		name: "auto-imports",

		async buildStart() {
			await refreshMap();
		},

		configureServer(server) {
			server.watcher.on("add", () => refreshMap(server));
			server.watcher.on("change", () => refreshMap(server));
			server.watcher.on("unlink", () => refreshMap(server));
		},

		async transform(code, id) {
			const cleanId = id.split("?")[0];
			if (!isSourceFile(cleanId, opts.extensions) || cleanId.includes("node_modules")) return null;

			const words = findUppercaseWords(code);
			let injected = "";

			for (const name of words) {
				if (!exportMap[name] || exportMap[name] === cleanId) continue;

				const isImported = new RegExp(`import\\s+[^\\n'"]*?\\b${name}\\b`).test(code);
				const isDeclared = new RegExp(`(?:const|let|var|function|class)[\\s\\{,]*\\b${name}\\b`).test(code);
				if (isImported || isDeclared) continue;

				const rel = relative(dirname(cleanId), exportMap[name])
					.replace(/\\/g, "/")
					.replace(/\.[jt]sx?$/, "");
				const path = rel.startsWith(".") ? rel : `./${rel}`;

				injected += `import ${name} from "${path}";\n`;
			}

			if (!injected) return null;

			return {
				code: injected + code,
				map: null
			};
		}
	};
}