import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, resolve, relative, dirname } from "node:path";
import esbuild from "esbuild";

const clean = file => resolve(file.split("?")[0]);
const slash = path => path.replace(/\\/g, "/");
const noExt = path => path.replace(/\.[jt]sx?$/, "");

const ids = code => {
	const cleanCode = code.replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, "");
	return [...new Set(cleanCode.match(/\b[A-Za-z_$][\w$]*\b/g) || [])];
};

const isSource = (file, exts, dts, srcPath) => {
	file = clean(file);
	return slash(file).startsWith(slash(resolve(srcPath)) + "/")
		&& file !== resolve(dts)
		&& !file.endsWith(".d.ts")
		&& exts.some(ext => file.endsWith(ext));
};

const loader = file => file.endsWith(".tsx") ? "tsx" : file.endsWith(".ts") ? "ts" : "jsx";

const sig = exports => exports.map(e => `${e.name}:${e.isDefault}`).sort().join("|");

const defaultName = code => {
	code = code.replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, "");
	return code.match(/export\s+default\s+(?:async\s+)?(?:function|class)\s+([A-Za-z_$][\w$]*)/)?.[1]
		|| code.match(/export\s+default\s+([A-Za-z_$][\w$]*)\s*;?/)?.[1]
		|| null;
};

async function walk(dir, exts, dts, srcDir) {
	try {
		const out = await Promise.all((await readdir(dir, { withFileTypes: true })).map(e => {
			if (e.name === "node_modules" || e.name.startsWith(".")) return [];
			const file = join(dir, e.name);
			return e.isDirectory() ? walk(file, exts, dts, srcDir) : clean(file);
		}));
		return out.flat().filter(file => isSource(file, exts, dts, srcDir));
	} catch {
		return [];
	}
}

async function parseExports(file, code) {
	file = clean(file);
	code ??= await readFile(file, "utf8");

	try {
		const result = await esbuild.build({
			stdin: { contents: code, sourcefile: file, resolveDir: dirname(file), loader: loader(file) },
			bundle: false,
			metafile: true,
			write: false,
			outfile: "x.js",
			format: "esm",
			logLevel: "silent"
		});

		return Object.values(result.metafile.outputs).flatMap(out => (out.exports || []).map(name => {
			const isDefault = name === "default";
			name = isDefault ? defaultName(code) : name;
			return name ? { name, file, isDefault, isLib: false } : null;
		}).filter(Boolean));
	} catch {
		return null;
	}
}

export default function autoImports(options = {}) {
	const libs = options.libs || (options.lib ? [options.lib] : []);
	const opts = {
		src: "src",
		dts: "src/global.d.ts",
		extensions: [".js", ".jsx", ".ts", ".tsx"],
		...options,
		libs: Array.isArray(libs) ? libs : [libs]
	};

	let map = {};
	let signatures = {};
	let error = null;
	let queue = Promise.resolve();
	let timer = null;
	let pageResetAt = 0;
	let viteServer = null;

	const dts = () => resolve(process.cwd(), opts.dts);
	const src = () => resolve(process.cwd(), opts.src);

	const sendOverlay = e => {
		viteServer?.ws.send({
			type: "error",
			err: {
				message: e.message,
				stack: e.stack || e.message,
				id: e.id || opts.dts,
				plugin: e.plugin || "auto-imports",
			},
		});
	};

	const fail = (msg, id) => {
		const e = new Error(msg);
		e.plugin = "auto-imports";
		e.id = id;
		error = e;
		sendOverlay(e);
	};

	const add = exp => {
		const old = map[exp.name];
		if (old && old.file !== exp.file) {
			fail(`Conflict for identifier "${exp.name}"\n\nPaths:\n1. ${old.file}\n2. ${exp.file}`, exp.file);
			return;
		}
		map[exp.name] = exp;
	};

	const writeDts = async () => {
		const dir = dirname(dts());
		let code = "// This file was generated by auto-imports\ndeclare global {";

		for (const [name, exp] of Object.entries(map)) {
			const path = exp.isLib
				? exp.file
				: (p => p.startsWith(".") ? p : `./${p}`)(slash(noExt(relative(dir, exp.file))));

			code += `\n\tvar ${name}: typeof import("${path}").${exp.isDefault ? "default" : name};`;
		}

		await mkdir(dir, { recursive: true });
		await writeFile(dts(), `${code}\n}\n\nexport {};`);
	};

	const resetPlugin = async () => {
		map = {};
		signatures = {};
		error = null;

		for (const lib of opts.libs) {
			if (!lib) continue;
			try {
				for (const name of Object.keys(await import(lib))) {
					if (name !== "default") add({ name, file: lib, isDefault: false, isLib: true });
				}
			} catch { }
		}

		for (const file of await walk(src(), opts.extensions, dts(), src())) {
			const exports = await parseExports(file);
			if (!exports) continue;
			signatures[file] = sig(exports);
			exports.forEach(add);
		}

		await writeDts();
	};

	const sync = task => queue = queue.then(task).catch(e => fail(e.message, opts.dts));

	const resetAll = async (server, reload = true) => {
		await sync(resetPlugin);
		if (error) return;
		server?.moduleGraph.invalidateAll?.();
		if (reload) server?.ws.send({ type: "full-reload" });
	};

	const pageRequest = req =>
		req.method === "GET"
		&& req.headers.accept?.includes("text/html")
		&& !req.url?.startsWith("/@");

	const scheduleReset = server => {
		clearTimeout(timer);
		timer = setTimeout(() => resetAll(server, true), 75);
	};

	return {
		name: "auto-imports",

		buildStart() {
			return sync(resetPlugin);
		},

		configureServer(server) {
			viteServer = server;
			server.middlewares.use(async (req, res, next) => {
				if (pageRequest(req) && Date.now() - pageResetAt > 250) {
					pageResetAt = Date.now();
					await resetAll(server, false);
				}
				next();
			});

			const structural = file => {
				if (isSource(file, opts.extensions, dts(), src())) scheduleReset(server);
			};

			server.watcher.on("add", structural);
			server.watcher.on("unlink", structural);
		},

		async handleHotUpdate(ctx) {
			const file = clean(ctx.file);
			if (!isSource(file, opts.extensions, dts(), src())) return;

			const exports = await parseExports(file, await ctx.read());
			if (!exports) return [];

			if (signatures[file] === sig(exports)) return;

			await resetAll(ctx.server, true);
			return [];
		},

		transform(code, id) {
			if (id.startsWith("\0") || id.startsWith("virtual:")) return null;

			const file = clean(id);
			if (file.includes("node_modules") || !isSource(file, opts.extensions, dts(), src())) {
				return null;
			}

			if (error) throw error;

			let imports = "";

			for (const name of ids(code)) {
				const exp = map[name];
				if (!exp || exp.file === file) continue;
				if (new RegExp(`import\\s+[^\\n'"]*\\b${name}\\b`).test(code)) continue;
				if (new RegExp(`(?:const|let|var|function|class)\\s+${name}\\b`).test(code)) continue;

				const path = exp.isLib
					? exp.file
					: (p => p.startsWith(".") ? p : `./${p}`)(slash(noExt(relative(dirname(file), exp.file))));

				imports += exp.isDefault
					? `import ${name} from "${path}";\n`
					: `import { ${name} } from "${path}";\n`;
			}

			return imports ? { code: imports + code, map: null } : null;
		}
	};
}